language: node_js
node_js:
- '10'
cache: npm
script:
- CI=false npm run build
branches:
  only:
  - master
  - prod
deploy:
- provider: firebase
  project: "charitydiscount"
  only: hosting:admin
  on:
    branch: prod
  skip_cleanup: true
  token:
    secure: 2xvcbmbV8mmFKDtslZ4Z0AYsreRMqCmstocOTyqjwcDUEpct2z/65U9TgmceKddhmcjA9m61FjDZpTKUl3hRpx72lphCaxj9vrFCVPQrmU0IkBzITAmR/NxaeAiWzYdtDyRGM4MgNaaY0wBqab3yXficO/mcij4qN4FcBhD700BajaMC3KtP7xv+kvhxRjJtqAGHlwmoLaXpnmEIhr3xnfO0hFI0348pnWzrYoiYJGAX5QTtUTKC9iUuBRHjzfZBCMf9NREHhoIe9DXqlfDgkF8XilvPvr6zh2/oYD/uQY9nv1v2I9usVNDuZ+4SrHfpHsrl6ATg5wgQm7hPF/LGq7VcpCLEy7STY9JiW0UiRKH9adPMxi3PdzFFQwWEECnTc6jjzOMFjVyDQrDmyx5TiNhzBkxlExbxfajSUk/RjDRu15LU/8E+S0OEsx+KnOHb9eWM5vjTACt4NHeQdSydgqsxJ4a660PLZwi9WUJ8YZh1O9m708aZltCxs23kiil/8YpLt8iarHRh+/L8F7zUhouA4sKec59QfwWaRDcVZV4zdQsT9jiBfbIKYuprkb6LQEk/9oe0Srcuf+DdSjhqjUeuxjz6ylh4KWqU8CTgvoAcfGZnz5JoA24L5uncrizio0SQZdUrCB6s606g4p6O6LHcYQSABdy/IaidFT7Z+Rc=
- provider: firebase
  project: "charitydiscount-test"
  only: hosting:admin
  on:
    branch: master
  skip_cleanup: true
  token:
    secure: r2KGHsowzFekL6w2yVOMANFGWEzPQdYKhR4cRUjtb/VOGPdebwc8j31S80/ETCnAiwGHj6XpciwDqNRYsrRrtREXgLjrtUxTHObrewvGniq1rltlCkEW1WzUKppQdLsuT12yB51Osk6uiz1hv1pY5WT2tOR+6BUr+Eh0VL5ydNKRViDbZJIlfACUsToSs+bHhPPQNyjOqLQxmUgwSeNzmgihMaT75Iw5zrhiUFc7/Iz2tVh4d/s0CHSII03ZJsOcBU1e7IdFAByvzVdbdlDUqiH6TY+rqu4aIulEl0VEWNzT1lRFKbRdKXOePiw1Mt8VvCDK+qouI2kWpKTJbpTMovA+rOqDHgA2U+AQPfOFMcx+ClhjVKkFQ21DBVTdsVc4PA0//8F4Va8GplxQ9EiRYvG+rqs2jxbkEuSO41tCyTzEOH4wJ3K0EZ26LlsPQUZGk2EidwqXipVEVZQ/KzdKfTGSsMQZ6O4OOr6cK/5HPpavAo9SijnJJSR6hl1RjSXt+ZdXLifsZVlChlCMljYfQs9aGFKV+yZSvYme+7RWOVcXsnmOTm2ohaLoUKBnQyVwhg9jW/htpdJwDhhSa4gJH7qD2hTCskoi4VX2aupJwIXbpHKJcfdJsnGpyaN0ciY2/FrNbsVN/fhfHBZHbqPJ5uX+ky/owCm5TXHbbKqy914=
