export enum LoginActionTypes {
    SET_LOGGED_USER_ACTION = 'SET_LOGGED_USER_ACTION',
    RESET_LOGGED_USER_ACTION = 'RESET_LOGGED_USER_ACTION',
}

export enum AuthActionTypes {
    SET_AUTHORIZED_USER_ACTION = 'SET_AUTHORIZED_USER_ACTION',
}
